apiVersion: apps/v1
kind: Deployment
metadata:
  name: horusec-admin
spec:
  template:
    spec:
      containers:
        - name: horusec-admin
          imagePullPolicy: Never
          env:
            - name: LOG_LEVEL
              value: trace
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: JAEGER_ENDPOINT
              value: http://jaeger-collector.tracing:14268/api/traces
