resources:
- ../../base
patchesStrategicMerge:
- deployment_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: horusec-system
images:
- name: horuszup/horusec-admin
  newTag: latest
