---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: horusec-admin
  labels:
    app: horusec-admin
spec:
  replicas: 1
  template:
    metadata:
      name: horusec-admin
      labels:
        app: horusec-admin
    spec:
      containers:
        - name: horusec-admin
          image: horuszup/horusec-admin:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
      restartPolicy: Always
  selector:
    matchLabels:
      app: horusec-admin